[app]
uuid_node_index = 0

[db]
type = 'postgres'
is_test = false
host = '127.0.0.1'
port = 5432
user = 'postgres'
password = '123456'
schema = 'public'
db_name = 'token-engine'
ssl_mode = 'disable'

[http]
enable = true
port = 8082
multipart_memory = 1073741824
read_timeout = '3m20s'
write_timeout = '3m20s'
tls_enable = false
tls_cert_file_path = ''
tls_key_file_path = ''
jwt_token_valid_duration = '30m0s'
jwt_token_hmac_key = '_awsd_2024'

[cache]
expired_time = '24h0m0s'
cleanup_interval = '48h0m0s'

[log]
level = 'info'
file_name = 'token-engine'
max_age = '168h0m0s'
max_size = '64mb'
rotation_time = '24h0m0s'
enable_color = true
enable_caller = false
disable_timestamp = false

[log.module_level_map]
api = 'debug'
app = 'info'
sidecar = 'debug'

[file]
upload_path = './static'
visit_url_prefix = 'http://10.1.8.181:8082/api/v1/rwa/images/'

[contract]
rbu_router_contract_addr = '0x0165878A594ca255338adfa4d48449f69242Eb8F'
vault_router_contract_addr = ''
escrow_factory_contract_addr = ''
pricer_factory_contract_addr = ''
rbu_manager_factory_contract_addr = ''
rbu_token_factory_contract_addr = ''
asset_token_contract_addr = '0x5FbDB2315678afecb367f032d93F642f64180aa3'

[biz]
rbu_manager_address = '0x79a1215469FaB6f9c63c1816b45183AD3624bE34'
drds_endpoints = 'http://10.1.2.131:6460'
enable_launch_whitelist = false

[mq]
enable = false
host = 'localhost'
port = 4150
topic = 'token_engine'
secret = '33333'

[key_guardian]
    encrypt_type = 0
    encrypt_pwd = 'alphr@0326.token_engine'

[jupiter]
    stable_urls = [
        'https://quote-api.jup.ag/v6'
    ]
    unstable_url = [
        'https://quote-api.jup.ag/v6'
    ]

[solana]
    vault_program_id = '5CuHZfPdG9cW1HV8Xh41o97LTgeJevcZEjEDr8re1L7W'
    raydium_cp_swap_program_id = 'CPMDWBwJDtYax9qW7AyRuVC19Cc4L4Vcy4n2BHAbHkCW'
    raydium_amm_config_account_id = '9zSzfkYy6awexsHvmggeH36pfVUdDGyCcwmjT3AQPBj6'
    raydium_create_pool_fee_receive_account_id = 'G11FKBRaAkHAKuLCgLM6K6NUc9rTjPAznRCjZifrTQe2'
    send_tx_http_rpcs = [
        'https://api.devnet.solana.com',
        'https://solana-devnet.g.alchemy.com/v2/TGzvic4SbTk5vQO48f-seqFIZewai5cu'
#        'https://mainnet.helius-rpc.com/?api-key=dc144c4f-1adc-4fb8-ac3f-fab305349953'
    ]
    stable_http_rpcs = [
        'https://api.devnet.solana.com',
        'https://solana-devnet.g.alchemy.com/v2/TGzvic4SbTk5vQO48f-seqFIZewai5cu'
#        'https://mainnet.helius-rpc.com/?api-key=dc144c4f-1adc-4fb8-ac3f-fab305349953'
    ]
    unstable_http_rpcs = [
        'https://api.devnet.solana.com',
        'https://solana-devnet.g.alchemy.com/v2/TGzvic4SbTk5vQO48f-seqFIZewai5cu'
#        'https://mainnet.helius-rpc.com/?api-key=dc144c4f-1adc-4fb8-ac3f-fab305349953'
    ]
    ws_rpcs = [
        'wss://api.devnet.solana.com'
#        'wss://solana-devnet.g.alchemy.com/v2/TGzvic4SbTk5vQO48f-seqFIZewai5cu'
#        'wss://mainnet.helius-rpc.com/?api-key=dc144c4f-1adc-4fb8-ac3f-fab305349953'
    ]
    http_timeout = '1m40s'

    [solana.jito_config]
        DisableTipTracker = true
        TipStreamURL = 'wss://bundles.jito.wtf/api/v1/bundles/tip_stream'
        CollectTipInfoInterval = 60000000000

    [[solana.jito_config.Rpcs]]
        Endpoint = 'https://frankfurt.mainnet.block-engine.jito.wtf'
        APIKey = ''

    [[solana.jito_config.Rpcs]]
        Endpoint = 'https://mainnet.block-engine.jito.wtf'
        APIKey = ''

    [[solana.jito_config.Rpcs]]
        Endpoint = 'https://amsterdam.mainnet.block-engine.jito.wtf'
        APIKey = ''

    [[solana.jito_config.Rpcs]]
        Endpoint = 'https://ny.mainnet.block-engine.jito.wtf'
        APIKey = ''

    [[solana.jito_config.Rpcs]]
        Endpoint = 'https://tokyo.mainnet.block-engine.jito.wtf'
        APIKey = ''

    [solana.bloxroute_config]
        FrontRunningProtection = false
        UseStakedRPCs = true
        FastBestEffort = false
        DisableTipTracker = true
        TipStreamURL = 'wss://ny.solana.dex.blxrbdn.com/ws'
        TipStreamApiKey = 'MzY2MGQyNDUtNTE4OS00Yzc4LTk5ZjItNWE0Y2M4YWU0YTlkOjBhMDczNGI0YTRiOWE1OTBjMmMxMjhmNjVlOGE2YWFl'
        CollectTipInfoInterval = 60000000000

    [[solana.bloxroute_config.Rpcs]]
        Endpoint = 'https://uk.solana.dex.blxrbdn.com'
        APIKey = 'MzY2MGQyNDUtNTE4OS00Yzc4LTk5ZjItNWE0Y2M4YWU0YTlkOjBhMDczNGI0YTRiOWE1OTBjMmMxMjhmNjVlOGE2YWFl'

    [[solana.bloxroute_config.Rpcs]]
        Endpoint = 'https://ny.solana.dex.blxrbdn.com'
        APIKey = 'MzY2MGQyNDUtNTE4OS00Yzc4LTk5ZjItNWE0Y2M4YWU0YTlkOjBhMDczNGI0YTRiOWE1OTBjMmMxMjhmNjVlOGE2YWFl'

[submitter]
    is_test = false
    [submitter.tip_percentage]
        low = 50
        avg = 75
        high = 95